"""empty message

Revision ID: 584d213a748d
Revises: c198929399c2
Create Date: 2016-03-06 18:08:49.876548

"""

# revision identifiers, used by Alembic.
revision = '584d213a748d'
down_revision = 'c198929399c2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_ribbon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('abbr', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile_social',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user_profile', sa.Column('company', sa.String(length=50), nullable=True))
    op.add_column('user_profile', sa.Column('title', sa.String(length=50), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'title')
    op.drop_column('user_profile', 'company')
    op.drop_table('profile_social')
    op.drop_table('profile_ribbon')
    ### end Alembic commands ###
