"""empty message

Revision ID: 6bf4c8b05d71
Revises: e3f9a9f2c823
Create Date: 2016-02-09 17:07:57.309125

"""

# revision identifiers, used by Alembic.
revision = '6bf4c8b05d71'
down_revision = 'e3f9a9f2c823'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_gdg_help_desk', sa.Column('article_password', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_gdg_help_desk', 'article_password')
    ### end Alembic commands ###
