"""empty message

Revision ID: b0a2de758473
Revises: 6bf4c8b05d71
Create Date: 2016-02-21 15:47:00.084407

"""

# revision identifiers, used by Alembic.
revision = 'b0a2de758473'
down_revision = '6bf4c8b05d71'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=30), nullable=True),
    sa.Column('title_desc', sa.String(length=50), nullable=True),
    sa.Column('content', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member_portfolio',
    sa.Column('portfolio_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('member_portfolio')
    op.drop_table('portfolio')
    ### end Alembic commands ###
