"""empty message

Revision ID: e19fb4b3c2c2
Revises: bef45169c904
Create Date: 2016-02-08 15:18:34.703918

"""

# revision identifiers, used by Alembic.
revision = 'e19fb4b3c2c2'
down_revision = 'bef45169c904'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_gdg_help_desk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('help_title', sa.String(length=200), nullable=True),
    sa.Column('help_content', sa.Text(), nullable=True),
    sa.Column('author_name', sa.String(length=20), nullable=True),
    sa.Column('author_univ', sa.String(length=30), nullable=True),
    sa.Column('author_major', sa.String(length=30), nullable=True),
    sa.Column('author_ip', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user_table', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('user_table', sa.Column('last_login', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_table', 'last_login')
    op.drop_column('user_table', 'is_active')
    op.drop_table('t_gdg_help_desk')
    ### end Alembic commands ###
